---- EXERCISE 1 QUESTION 1
--SELECT
--  CPS.NAME_OF_SCHOOL,
--  CPS.COMMUNITY_AREA_NAME,
--  CPS.AVERAGE_STUDENT_ATTENDANCE,
--  CD.HARDSHIP_INDEX
--FROM
--  CHICAGO_PUBLIC_SCHOOLS AS CPS
--  LEFT JOIN CENSUS_DATA AS CD ON CPS.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER
--WHERE
--  CD.HARDSHIP_INDEX = 98
  
  
---- EXERCISE 1 QUESTION 2
--SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CD.COMMUNITY_AREA_NAME, CCD.LOCATION_DESCRIPTION
--FROM CHICAGO_CRIME_DATA AS CCD
--LEFT JOIN CENSUS_DATA AS CD 
--ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER
--WHERE CCD.LOCATION_DESCRIPTION LIKE '%SCHOOL%'


---- EXERCISE 2 QUESTION 1 
--CREATE VIEW CHICAGO_SCHOOL_INFO
--(
--SCHOOL_NAME, SAFETY_RATING, FAMILY_RATING, ENVIRONMENT_RATING, INSTRUCTION_RATING, LEADERS_RATING, TEACHERS_RATING
--)
--AS SELECT NAME_OF_SCHOOL, SAFETY_ICON, FAMILY_INVOLVEMENT_ICON, ENVIRONMENT_ICON, INSTRUCTION_ICON, LEADERS_ICON, TEACHERS_ICON
--FROM CHICAGO_PUBLIC_SCHOOLS;
--
--SELECT * FROM CHICAGO_SCHOOL_INFO

--SELECT SCHOOL_NAME, LEADERS_RATING FROM CHICAGO_SCHOOL_INFO


-- EXERCISE 3 AND EXERCISE 4
--#SET TERMINATOR @
--CREATE OR REPLACE PROCEDURE UPDATE_LEADER_SCORE 
--(IN IN_SCHOOL_ID INT, IN IN_LEADER_SCORE INT)
--LANGUAGE SQL
--MODIFIES SQL DATA
--
--BEGIN
--
--  UPDATE CHICAGO_PUBLIC_SCHOOLS
--  SET LEADERS_SCORE = IN_LEADER_SCORE
--  WHERE SCHOOL_ID = IN_SCHOOL_ID;
--  
--  IF IN_LEADER_SCORE BETWEEN 0 AND 20 THEN
--  UPDATE CHICAGO_PUBLIC_SCHOOLS
--  SET LEADERS_ICON = 'VERY WEAK'
--  WHERE SCHOOL_ID = IN_SCHOOL_ID;
--
--  ELSEIF IN_LEADER_SCORE < 40 THEN
--  UPDATE CHICAGO_PUBLIC_SCHOOLS
--  SET LEADERS_ICON = 'WEAK'
--  WHERE SCHOOL_ID = IN_SCHOOL_ID;
--
--  ELSEIF IN_LEADER_SCORE < 60 THEN
--  UPDATE CHICAGO_PUBLIC_SCHOOLS
--  SET LEADERS_ICON = 'AVERAGE'
--  WHERE SCHOOL_ID = IN_SCHOOL_ID;
--  
--  ELSEIF IN_LEADER_SCORE < 80 THEN
--  UPDATE CHICAGO_PUBLIC_SCHOOLS
--  SET LEADERS_ICON = 'STRONG'
--  WHERE SCHOOL_ID = IN_SCHOOL_ID;
--  
--  ELSEIF IN_LEADER_SCORE < 100 THEN
--  UPDATE CHICAGO_PUBLIC_SCHOOLS
--  SET LEADERS_ICON = 'VERY STRONG'
--  WHERE SCHOOL_ID = IN_SCHOOL_ID;
--  
--  ELSE
--  ROLLBACK WORK;
--  
--  END IF; 
--  
--  COMMIT WORK;
--  
--END@          

--ALTER TABLE CHICAGO_PUBLIC_SCHOOLS
--    ALTER COLUMN LEADERS_ICON
--    SET DATA TYPE VARCHAR(11);

--CALL UPDATE_LEADER_SCORE(610038,101);
--SELECT SCHOOL_ID, LEADERS_ICON FROM CHICAGO_PUBLIC_SCHOOLS WHERE SCHOOL_ID = 610038
